### ISSUE TITLE
Be able to send very basic emails when someone clicks a button on the website.

### ISSUE THREAD

**Issue by g-rocket** [hmc-room-draw/room-draw#1]
We'll need to be able to send emails out to users for a variety of reasons. Therefore, we should figure out how to get our app to send an email when someone clicks a button.

**Comment by AliengirlLiv** [comment]
Implemented (although not integrated into main app) in branch olivias.

**Comment by hmc-cs-ox** [comment]
Integrated with a new model called Email with Emails controller now in branch pp.

**Comment by forLostLense** [comment]
Integrated with a new model called Email with Emails controller now in branch pp.
