### ISSUE TITLE
[BUG] Adjust login redirect and navbar home button route

### ISSUE THREAD

**Issue by jesswinssinger** [hmc-room-draw/room-draw#141]
If current_user is nil, Home should direct you to `sessions#new`
Elif current_user is admin, Home should direct you to `admin_home_path`
Else, Home should direct you to `dorms_path`

After a user logs in, they should be either directed to the `admin_home_path` or `dorms_path` depending on the type of user.

**Comment by g-rocket** [comment]
What about redirecting to the form if a user isn't an admin and hasn't completed the form?  Might as well throw that in while you're working on this if it's not too hard.
Also, we should probably add a link from the admin home page to fill out the form, as I doubt we want to force admins to fill out the form on their first login.  Maybe add a banner at the top of the admin home reminding them if they haven't yet?

**Comment by jesswinssinger** [comment]
@g-rocket Good call. Since I already put in a PR for the original stuff, I'll create a new issue for those additional fixes and make you a reviewer for the new PR tonight.

**Comment by jesswinssinger** [comment]
Merged!
