### ISSUE TITLE
CRUD for Pulls

### ISSUE THREAD

**Issue by vdhanan** [hmc-room-draw/room-draw#43]
Responsible for the Create/Edit, Notification, and Add functions from the Pull index view

**Comment by justinhyou** [comment]
The actions should be as follows:
"Create" or "Edit" should lead to the same interface (where "Edit" has pre-filled values):
1. Add button should allow a popover to add a specific person to a pull by specify person and room
2. View in table format the students, their numbers, their rooms, and an ssociated "Delete" button that removes a student from the pull
3. The overall "Pull number" field should initially start with the value of the pull requester (number and name)
4. The "Senior round" field should allow dropdown to select round number
5. Message field should have the custom message made by student (or blank for "create pull"), fully editable by admin

Additionally, when the "save" button for the create/edit pull is pushed, the students who were removed/edited or added should be sent an email notifying them of the change with a full receipt of the pull request.
