### ISSUE TITLE
Create list of specifications needed from database team

### ISSUE THREAD

**Issue by vdhanan** [hmc-room-draw/room-draw#5]
Things like admin/super-admin distinction

**Comment by jesswinssinger** [comment]
# Admin Database Specifications

## Users Table
- Should have (in addition to all columns necessary for a basic user) a **role_id column** with the possibility for the three following string values:
  * “basic”
  * “ASHMC”
  * “super-admin”
Where: as ranking increases, additional UI builds onto existing UI
- NO SEPARATE ADMIN USERS TABLE OR ROLES TABLE NEEDED

**Comment by vdhanan** [comment]
@sxmichaels
