### ISSUE TITLE
Begin designing admin UI

### ISSUE THREAD

**Issue by jesswinssinger** [hmc-room-draw/room-draw#6]
10/2/2017
By assumption of assigned roles ranging from super_admin to student, build basic admin pages for the following: 

1. listing of students who did not participate in room draw
2. form for forced room assignment
3. dashboard of housing requests
4. communication platform to email students from web page

**Comment by vdhanan** [comment]
@jesswinssinger : 1
@elfran : 3
@justinhyou : 4

**Comment by jesswinssinger** [comment]
I'll work on the page for scheduling/starting a room draw session.
